# -*- coding: utf-8 -*-
"""Topic Modelling-BerTopic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nxRxeQ0Ue7yJSycbFydM3L6YlocbZmHr

## Topic Modeling Using BerTopic (Bert Based model)

bert based model used for topic modelling.

1.Make use of Bert Embedding and plots our documents in High Dimensional vector(Vector embeddings).

2.Then, using clustring algorithm, creates clusters.

3.then finds the most frequent words within the cluster
"""

# !pip install bertopic

import pandas as pd
from bertopic import BERTopic

df = pd.read_csv("/content/tokyo_2020_tweets.csv")

docs = df.text.tolist()

docs = docs[0:6000]

model = BERTopic()

topics,probs = model.fit_transform(docs)

model.get_topic_freq().head(10) # topic -1 means "others" documents which not fit in any topic

model.transform("new_docs") #for predicting topics for new documents using our trained model

# #for saving model
# model.save()

# # for loading model
# BERTopic.load()

"""## Hyperparameters

>> language -> ["english","multilingual"]

>> min_topic_size -> minimum size of topic cluster

>> nr_topics -> No. of topics
"""

# Now we will see about UMAP and HDBSCAN, these two are seperate algorithms
# but we can make use of these two algos in our topic modelling with BerTopic

"""## UMAP

Umap model is used for Dimensonality reduction

Sometimes, it may happen that created dataset is of very high dimension, and can cause problems while clustering

so , umap model can help reduce the dimension
"""

from umap import UMAP

umap_model = UMAP(n_neighbors=10,metric = 'cosine') # now from this our model of UMAP is created

# now we can pass this Umap model as a parameter like below

model = BERTopic(umap_model=umap_model)

"""## HDBSCAN

Hierarchical Density-Based Spatial Clustering of Applications with Nois (HDBSCAN)
"""

from hdbscan import HDBSCAN

hdbscan_model = HDBSCAN(min_cluster_size=10,metric='euclidean')

model = BERTopic(hdbscan_model=hdbscan_model)